const express = require('express')
const dotenv = require("dotenv")
const mongoose = require("mongoose")
const app = express()
const productRouter = require('./routes/product')
const authRouter = require('./routes/auth')
const userRouter = require('./routes/user')
const cartRouter = require('./routes/cart')
const orderRouter = require('./routes/order')
const favouritesRouter = require('./routes/favourites');
const port = 3000
dotenv.config()
mongoose.connect(process.env.MONGO_URL).then(res => console.log("Connected")).catch(err => console.log("Err", err))
//app.get('/', (req, res) => res.send('Hello World!'))
app.use(express.json({ limit: "10mb" }))
app.use(express.urlencoded({ limit: "10mb", extended: true }))
app.use("/api/products", productRouter)
app.use("/api/users", userRouter)
app.use("/api/cart", cartRouter)
app.use("/api/orders", orderRouter)
app.use("/api/favourites", favouritesRouter)

app.use("/api/", authRouter)
app.listen(process.env.PORT || port, () => console.log(`Example app listening on port ${process.env.PORT}!`))